### PR TITLE
Add missed test package

### PR DESCRIPTION
**Pull request by r4ts0n**
`make test` requires `mock`

### CODE REVIEW

**Comment by zsiciarz** [comment]
Hi r4ts0n and thanks for the PR! However the omission of `mock` is intended as I mentioned before in #35. I support Python 2.7 only because sometimes I have to, otherwise I do my development on 3. If you take a look at tox.ini, you'll see mock being installed for old Python versions. Perhaps I should update the development docs to be more explicit about Py3-first approach.

**Comment by r4ts0n** [comment]
Understood, it would be great to have a Python 2 note about `pip install mock` in https://github.com/zsiciarz/django-envelope/blob/master/docs/development.rst

**Comment by zsiciarz** [comment]
If you have a note in mind, feel free to contribute it in a new PR. Otherwise I'll add a few words later today.

**Comment by zsiciarz** [comment]
FYI, I've added a paragraph about `mock` in bdb92a3886a2016f14ceb411b024eb0f1a80166a.

**Pull request closed without merging**
